/* ─── Tests — Milestone 1 model is frozen across Milestone 2 ──────────────
 *
 * Two guarantees, both against a GOLDEN file captured from the engine
 * BEFORE any Milestone 2 edit (test/fixtures/tissueLoadBaseline.v0.1.json,
 * generated by test/fixtures/captureTissueLoadBaseline.mjs at the commit
 * the file names). Expected values are therefore never computed by the
 * implementation under test.
 *
 *   1. Identical legacy inputs produce the baseline outputs, in full.
 *   2. Adding or changing ONLY rir / side / tempo / rom on otherwise
 *      identical inputs produces exactly the same outputs.
 *
 * Demo-fixture timestamps derive from local calendar dates, so sessions
 * are pinned to the fixed epoch literals the capture script used.
 * ───────────────────────────────────────────────────────────────────────── */

import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

import { estimateSessionTissueLoad, estimateSetTissueLoad } from "../js/tissue/loadEngine.js";
import { TISSUE_LOAD_MODEL_VERSION, EXERCISE_TISSUE_MAP_VERSION } from "../js/tissue/modelVersion.js";
import {
  DEMO_SESSION_COMPLETE, DEMO_SESSION_PARTIAL, DEMO_SESSION_LATER, DEMO_SESSION_B, DEMO_ACTIVE_SESSION,
  DEMO_SESSION_METADATA_B
} from "../js/dev/demoFixtures.js";
import { SET_METADATA_FIELDS, clearSetMetadata } from "../js/utils/setMetadata.js";

const GOLDEN = JSON.parse(readFileSync(new URL("./fixtures/tissueLoadBaseline.v0.1.json", import.meta.url), "utf8"));

const SESSIONS = {
  DEMO_SESSION_COMPLETE: DEMO_SESSION_COMPLETE,
  DEMO_SESSION_PARTIAL: DEMO_SESSION_PARTIAL,
  DEMO_SESSION_LATER: DEMO_SESSION_LATER,
  DEMO_SESSION_B: DEMO_SESSION_B,
  DEMO_ACTIVE_SESSION: DEMO_ACTIVE_SESSION,
  SYNTHETIC_MIXED: GOLDEN.syntheticMixedInput
};
const CONTEXTS = { explicit180: { bodyMass: 180 }, none: undefined };

function clone(x) { return JSON.parse(JSON.stringify(x)); }
function pinned(s) { return Object.assign({}, s, GOLDEN.pinnedTimestamps); }

/* Deep-copy a session and stamp metadata onto every set, alternating
   values so every field and both RIR bounds are exercised. */
function decorate(session, variant) {
  const out = clone(session);
  let i = 0;
  out.exercises.forEach(function(ex) {
    (ex.sets || []).forEach(function(set) {
      i++;
      if (variant === "all") {
        set.rir = i % 6;                                   // 0..5
        set.side = ["left", "right", "bilateral"][i % 3];
        set.tempo = { eccentricSeconds: 3, pauseSeconds: i % 2, concentricSeconds: 1 };
        set.rom = ["partial", "standard", "full"][i % 3];
      } else if (variant === "rirOnly") {
        set.rir = i % 2 === 0 ? 0 : 5;
      } else if (variant === "partialTempo") {
        set.tempo = { eccentricSeconds: 4 };
      } else if (variant === "sides") {
        set.side = i % 2 === 0 ? "left" : "right";
      } else if (variant === "malformed") {
        set.rir = "2abc"; set.side = "Left"; set.tempo = "3-1-1"; set.rom = 7;
      }
    });
  });
  return out;
}

// ── 1. legacy inputs reproduce the golden outputs ───────────────────────

test("the golden file was captured from the pinned model version", function() {
  assert.equal(TISSUE_LOAD_MODEL_VERSION, "tissue-load-v0.1");
  assert.equal(EXERCISE_TISSUE_MAP_VERSION, "exercise-tissue-map-v0.1");
  assert.match(GOLDEN.generatedFrom, /^[0-9a-f]{40}$/);
  assert.equal(Object.keys(GOLDEN.sessions).length, 6);
  assert.equal(Object.keys(GOLDEN.sets).length, 6);
});

Object.keys(SESSIONS).forEach(function(name) {
  Object.keys(CONTEXTS).forEach(function(ctxName) {
    test("legacy session " + name + " [" + ctxName + "] reproduces the pre-Milestone-2 output exactly", function() {
      const actual = estimateSessionTissueLoad(pinned(SESSIONS[name]), CONTEXTS[ctxName]);
      assert.deepEqual(clone(actual), GOLDEN.sessions[name][ctxName]);
    });
  });
});

test("legacy single-set cases reproduce the pre-Milestone-2 output exactly", function() {
  Object.keys(GOLDEN.sets).forEach(function(k) {
    const c = GOLDEN.sets[k];
    const actual = estimateSetTissueLoad(c.input.exercise, c.input.set, c.input.context === null ? undefined : c.input.context);
    assert.deepEqual(clone(actual), c.output, k);
  });
});

// ── 2. metadata is invisible to the model ───────────────────────────────

["all", "rirOnly", "partialTempo", "sides", "malformed"].forEach(function(variant) {
  Object.keys(SESSIONS).forEach(function(name) {
    Object.keys(CONTEXTS).forEach(function(ctxName) {
      test("adding '" + variant + "' metadata to " + name + " [" + ctxName + "] changes nothing", function() {
        const decorated = decorate(pinned(SESSIONS[name]), variant);
        const actual = estimateSessionTissueLoad(decorated, CONTEXTS[ctxName]);
        assert.deepEqual(clone(actual), GOLDEN.sessions[name][ctxName]);
        // and the decorated input was not mutated by the engine
        assert.deepEqual(decorated, decorate(pinned(SESSIONS[name]), variant));
      });
    });
  });
});

test("changing only metadata between two otherwise identical sessions yields identical outputs", function() {
  const a = decorate(pinned(DEMO_SESSION_PARTIAL), "all");
  const b = clone(a);
  b.exercises[0].sets[0].rir = 5 - b.exercises[0].sets[0].rir;
  b.exercises[0].sets[0].side = "left";
  b.exercises[0].sets[0].tempo = { eccentricSeconds: 10, pauseSeconds: 10, concentricSeconds: 10 };
  b.exercises[0].sets[0].rom = "partial";
  delete b.exercises[1].sets[0].tempo;
  assert.deepEqual(estimateSessionTissueLoad(a, { bodyMass: 180 }), estimateSessionTissueLoad(b, { bodyMass: 180 }));
});

test("the metadata fixture scores exactly like its metadata-stripped twin, and an incomplete set with metadata stays excluded", function() {
  const withMeta = pinned(DEMO_SESSION_METADATA_B);
  const stripped = clone(withMeta);
  stripped.exercises.forEach(function(ex) { ex.sets = ex.sets.map(clearSetMetadata); });
  const rWith = estimateSessionTissueLoad(withMeta, { bodyMass: 142 });
  const rStripped = estimateSessionTissueLoad(stripped, { bodyMass: 142 });
  assert.deepEqual(rWith, rStripped);

  // Lunge: 2 done, 1 incomplete (the incomplete one carries side+rir).
  const lunge = rWith.exercises.filter(function(e) { return e.exerciseName === "Lunge"; })[0];
  assert.equal(lunge.completedSets, 2);
  assert.equal(lunge.incompleteSets, 1);
  const lungeEvents = rWith.events.filter(function(ev) { return ev.provenance.exerciseName === "Lunge"; });
  assert.deepEqual(Array.from(new Set(lungeEvents.map(function(ev) { return ev.provenance.setIndex; }))).sort(), [0, 1]);
});

test("no event or provenance carries metadata, and no side-based splitting happens", function() {
  const r = estimateSessionTissueLoad(decorate(pinned(DEMO_SESSION_B), "all"), { bodyMass: 180 });
  r.events.forEach(function(ev) {
    assert.deepEqual(Object.keys(ev).sort(), ["confidence", "modelVersion", "provenance", "sourceType", "timestamp", "tissueId", "workload", "workloadUnit"]);
    assert.deepEqual(Object.keys(ev.provenance).sort(), ["exerciseId", "exerciseIndex", "exerciseName", "sessionId", "setIndex"]);
    SET_METADATA_FIELDS.forEach(function(f) { assert.equal(f in ev, false); assert.equal(f in ev.provenance, false); });
  });
  assert.equal(r.events.length, GOLDEN.sessions.DEMO_SESSION_B.explicit180.events.length);
});

test("set-level: metadata on a single set leaves every output field identical", function() {
  Object.keys(GOLDEN.sets).forEach(function(k) {
    const c = GOLDEN.sets[k];
    const decoratedSet = Object.assign({}, c.input.set, {
      rir: 3, side: "left", tempo: { eccentricSeconds: 3, pauseSeconds: 0, concentricSeconds: 1 }, rom: "partial"
    });
    const actual = estimateSetTissueLoad(c.input.exercise, decoratedSet, c.input.context === null ? undefined : c.input.context);
    assert.deepEqual(clone(actual), c.output, k);
  });
});

test("the engine source does not read the metadata fields (source guard)", function() {
  const src = readFileSync(new URL("../js/tissue/loadEngine.js", import.meta.url), "utf8");
  const code = src.replace(/\/\*[\s\S]*?\*\//g, "").replace(/\/\/.*$/gm, "");   // strip comments
  ["\\.rir\\b", "\\.side\\b", "\\.tempo\\b", "\\.rom\\b", "\\[\"rir\"\\]", "\\[\"side\"\\]", "\\[\"tempo\"\\]", "\\[\"rom\"\\]"]
    .forEach(function(pattern) {
      assert.equal(new RegExp(pattern).test(code), false, "loadEngine.js must not reference " + pattern);
    });
  const tissueDir = ["exerciseTissueMap.js", "modelVersion.js", "tissueDefinitions.js", "uncertainty.js"];
  tissueDir.forEach(function(f) {
    const s = readFileSync(new URL("../js/tissue/" + f, import.meta.url), "utf8");
    assert.equal(s.indexOf("setMetadata"), -1, f + " must not import the metadata module");
  });
});
