"""Pure, deterministic research domain logic (no I/O, no clock, no database).

The squat modules (pose_frame, geometry, kinematics, side_selection,
smoothing, calibration, segmentation, capture_quality, squat_analysis,
protocol) are an independent Python implementation of the Milestone 6
semantics ``squat-kinematics-v0.2`` / ``movement-assessment-v0.1``. Every
rule, threshold and tie-break mirrors the JavaScript source in
``js/movement/``; tests/test_m6_parity.py checks the two against shared
fixtures generated by the JavaScript code itself.
"""
