"""Restricted temporary storage for raw research video.

Raw video is temporary processing input only. It exists as ONE file in an
application-specific directory, from upload until the worker finishes (or
the job is cancelled/expired), and is then deleted.

* The directory is created with mode 0700, must be a real directory (not a
  symlink) owned by the current user, and holds nothing else of ours.
* File names are generated by the OS (``tempfile.mkstemp``, mode 0600) and
  never derived from anything the client sent: the uploaded filename is
  ignored entirely.
* The API holds an advisory file lock during intake. The stale-file sweep
  skips locked files even if a slow upload has not written for 10 minutes.
* The job row stores only the opaque token (basename); resolving a token
  re-validates it against a strict pattern, so a tampered row cannot point
  outside the directory.
* ``sweep_stale`` deletes only files that match our token pattern, inside
  our directory, older than the age limit and not claimed by an active job
  — never arbitrary system temp files.

Limitation: ``try/finally`` cannot run if the process is killed or the
machine loses power. Such files are removed by the startup sweep and the
periodic sweep of the worker (bounded by ``upload_max_age_s``) or by the
lease-expiry recovery of the job that owns them.
"""

from __future__ import annotations

import contextlib
import fcntl
import os
import re
import stat
import tempfile
import time
from collections.abc import Iterable
from pathlib import Path
from typing import Final

TOKEN_PREFIX: Final = "rv-"  # noqa: S105 - a file-name prefix, not a secret
TOKEN_SUFFIX: Final = ".upload"  # noqa: S105
TOKEN_PATTERN: Final = re.compile(r"^rv-[A-Za-z0-9_]{8,64}\.upload$")


class UploadDirError(RuntimeError):
    pass


def ensure_upload_dir(path: Path) -> Path:
    """Create/verify the application temp directory (0700, owned by us)."""
    path = Path(path)
    try:
        path.mkdir(mode=0o700, parents=True, exist_ok=True)
    except OSError as exc:  # pragma: no cover - environment failure
        raise UploadDirError("cannot create upload directory") from exc
    st = os.lstat(path)
    if stat.S_ISLNK(st.st_mode) or not stat.S_ISDIR(st.st_mode):
        raise UploadDirError("upload directory must be a real directory, not a symlink")
    if st.st_uid != os.getuid():
        raise UploadDirError("upload directory is owned by another user")
    if stat.S_IMODE(st.st_mode) != 0o700:
        os.chmod(path, 0o700)
    return path


def create_upload_file(upload_dir: Path) -> tuple[str, int]:
    """Create an empty 0600 file; returns (token, open file descriptor)."""
    fd, full = tempfile.mkstemp(prefix=TOKEN_PREFIX, suffix=TOKEN_SUFFIX, dir=str(upload_dir))
    os.fchmod(fd, 0o600)
    # The API holds this lock until intake finishes. A stale-file sweep in
    # another process must never unlink an upload that is merely stalled.
    fcntl.flock(fd, fcntl.LOCK_EX)
    token = os.path.basename(full)
    if not TOKEN_PATTERN.match(token):  # pragma: no cover - mkstemp contract
        os.close(fd)
        os.unlink(full)
        raise UploadDirError("unexpected temporary file name")
    return token, fd


def is_valid_token(token: object) -> bool:
    return isinstance(token, str) and bool(TOKEN_PATTERN.match(token))


def resolve_token(upload_dir: Path, token: str) -> Path:
    if not is_valid_token(token):
        raise UploadDirError("invalid upload token")
    path = Path(upload_dir) / token
    if path.parent.resolve() != Path(upload_dir).resolve():  # pragma: no cover - pattern forbids separators
        raise UploadDirError("upload token escapes the upload directory")
    return path


def delete_upload(upload_dir: Path, token: str | None) -> bool:
    """Delete one upload file. Idempotent; returns True if a file was removed."""
    if not token or not is_valid_token(token):
        return False
    path = resolve_token(upload_dir, token)
    try:
        os.unlink(path)
        return True
    except FileNotFoundError:
        return False


def upload_exists(upload_dir: Path, token: str | None) -> bool:
    if not token or not is_valid_token(token):
        return False
    return resolve_token(upload_dir, token).exists()


def list_uploads(upload_dir: Path) -> list[str]:
    try:
        names = os.listdir(upload_dir)
    except FileNotFoundError:
        return []
    return sorted(n for n in names if is_valid_token(n))


def sweep_stale(upload_dir: Path, *, max_age_s: float, keep: Iterable[str], now: float | None = None) -> list[str]:
    """Delete our upload files older than ``max_age_s`` that are not in ``keep``."""
    keep_set = set(keep)
    current = time.time() if now is None else now
    removed: list[str] = []
    for name in list_uploads(upload_dir):
        if name in keep_set:
            continue
        path = Path(upload_dir) / name
        try:
            fd = os.open(path, os.O_RDONLY | os.O_NOFOLLOW)
        except OSError:
            continue
        try:
            try:
                fcntl.flock(fd, fcntl.LOCK_EX | fcntl.LOCK_NB)
            except BlockingIOError:
                continue  # still being written by an API process
            st = os.fstat(fd)
            if not stat.S_ISREG(st.st_mode) or current - st.st_mtime < max_age_s:
                continue
            # Keep the checked inode attached to this path until unlink.
            with contextlib.suppress(FileNotFoundError):
                linked = os.lstat(path)
                if (linked.st_dev, linked.st_ino) == (st.st_dev, st.st_ino):
                    os.unlink(path)
                    removed.append(name)
        finally:
            os.close(fd)
    return removed
